name: Job Collection

on:
  repository_dispatch:
jobs:
  one:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Dispatch workflow
        if: github.event.client_payload.job == "one"
        run: |
          git branch --show-current
          echo "Dispatched One"
  two:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Dispatch workflow
        if: github.event.client_payload.job == "two"
        run: |
          git branch --show-current
          echo "Dispatched Two"